apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes      
      rolearn: arn:aws:iam::504477186992:role/KarpenterNodeRole
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::504477186992:role/eksctl-vagrant-karpenter-demo-nod-NodeInstanceRole-W01URINTS27
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::504477186992:role/KarpenterNodeRole-vagrant-karpenter-demo
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system