apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes      
      rolearn: arn:aws:iam::REPLACE_AWS_ACCOUNT_ID:role/KarpenterNodeRole
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::REPLACE_AWS_ACCOUNT_ID:role/REPLACE_NODEINSTANCE_ROLE
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::REPLACE_AWS_ACCOUNT_ID:role/KarpenterNodeRole-REPLACTE_CLUSTER_NAME
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system