apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: karpenter-demo
  region: us-east-2
  tags: 
    karpenter: nonprod
  version: "1.21"
iam:
  withOIDC: true
nodeGroups:
  - name: karpenter-demo-ng
    amiFamily: AmazonLinux2
    instanceType: m5.large
    desiredCapacity: 1
    minSize: 1
    maxSize: 10
    privateNetworking: true
    ssh:
      publicKeyName: karpenter_ec2_key
vpc:
  id: vpc-0fd823b0fc34a656f
  subnets:
    private:
      us-east-2a:
        id: subnet-09ca01d988070101a
      us-east-2b:
        id: subnet-03c4728afe5c50608
      us-east-2c:
        id: subnet-0814830dcfd6a7ba7