apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: ${CLUSTER_NAME}
  region: ${region_name}
  tags: 
    karpenter: nonprod
  version: "1.21"
iam:
  withOIDC: true
nodeGroups:
  - name: ${CLUSTER_NAME}-ng
    amiFamily: AmazonLinux2
    instanceType: m5.large
    desiredCapacity: 1
    minSize: 1
    maxSize: 10
    privateNetworking: true
    ssh:
      publicKeyName: ${karpenter_key_name}
vpc:
  id: ${get_vpc_id}
  subnets:
    private:
      ${region_name}a:
        id: ${az_one_subnet}
      ${region_name}b:
        id: ${az_two_subnet}
      ${region_name}c:
        id: ${az_three_subnet}