AWSTemplateFormatVersion: '2010-09-09'
Resources:
  # create InstanceProfile wrapper on NodeRole
  KarpenterNodeInstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      InstanceProfileName: "KarpenterNodeInstanceProfile"
      Path: "/"
      Roles:
        - Ref: "KarpenterNodeRole"
  # create role with basic permissions for EKS node
  KarpenterNodeRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: "KarpenterNodeRole"
      Path: /
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                !Sub "ec2.${AWS::URLSuffix}"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/AmazonEKSWorkerNodePolicy"
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/AmazonEKS_CNI_Policy"
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly"
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/AmazonSSMManagedInstanceCore"
  MyLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        KeyName: karpenter_ec2_key
        IamInstanceProfile:
          # Get ARN of InstanceProfile defined above
          Arn: !GetAtt
            - KarpenterNodeInstanceProfile
            - Arn
        ImageId: ami-04635d3effed08298
        UserData: "IyEvYmluL2Jhc2gKc2V0IC1leApDTFVTVEVSX05BTUU9J2thcnBlbnRlci1kZW1vJwpBUElfU0VSVkVSX1VSTD1odHRwczovLzE5MzE4RTM1RTUzNDRCNjNDRkRERTI0NkE1QjkwQzAwLnNrMS51cy1lYXN0LTIuZWtzLmFtYXpvbmF3cy5jb20KQjY0X0NMVVNURVJfQ0E9TFMwdExTMUNSVWRKVGlCRFJWSlVTVVpKUTBGVVJTMHRMUzB0Q2sxSlNVTTFla05EUVdNclowRjNTVUpCWjBsQ1FVUkJUa0puYTNGb2EybEhPWGN3UWtGUmMwWkJSRUZXVFZKTmQwVlJXVVJXVVZGRVJYZHdjbVJYU213S1kyMDFiR1JIVm5wTlFqUllSRlJKZUUxVVNYbE9la2wzVFZSak1VNUdiMWhFVkUxNFRWUkplVTVVU1hkTlZHTXhUa1p2ZDBaVVJWUk5Ra1ZIUVRGVlJRcEJlRTFMWVROV2FWcFlTblZhV0ZKc1kzcERRMEZUU1hkRVVWbEtTMjlhU1doMlkwNUJVVVZDUWxGQlJHZG5SVkJCUkVORFFWRnZRMmRuUlVKQlRHMUVDaTlwV1VwTk1HbDZjblZNUVhSeVZEYzNaREl4VEdKNVdWVjRjVVp3TW5GVU5scGpMMHBLYjI5c04yTnhUM0JFTlRJM2VqTTBRa1oyYWxCQ1JFbGFiSG9LYkZSbmMzSk5ZM2QwTUZOck4wbzFSV0ZEYWxGRU1XSTNUREE0T0VVMFRqSlZlWE5FZW1wTlkzZHVabmxUV1M5WFMwOXhlbkJ6TDBwWU0xcElTa3Q0UVFwRlRIbHZhRUZCVGxWcFRtNXdNVlF2VDBaNEsyaHZiMkZCZGt4S1R6QlJUa05pYWtwQ04zZFdVemhRYnpKWFNIUnliMFJuTTBOM01rbzFMMEUwYm14NUNqTjZWMU5WUmtkcWJpdEpPR2hGZGxsSmJIYzRUMGhNVmtaQmNrSTBVbmxLU2psUmFtSnhTR3N5TUhCalF5OXJhazlpV1d0WE5Ia3dPVmw1VEdoM2RVa0tZV05pZFZKcU9WSk5XSEUyUlVoc01sTmtRVEF6VjFkMU1VbEdaRUZMVW5aeVdURXZNbTlvV1RVNVlrTkJibGxTUjFFMVkyZEJRMVJLWmk5RFJraEdWZ3BKYVc5MlZHbHNPSFZEVG5waU5uQlBiRzB3UTBGM1JVRkJZVTVEVFVWQmQwUm5XVVJXVWpCUVFWRklMMEpCVVVSQlowdHJUVUU0UjBFeFZXUkZkMFZDQ2k5M1VVWk5RVTFDUVdZNGQwaFJXVVJXVWpCUFFrSlpSVVpNWm1JNVptNW5kaXRDY2pJd1kxUTNZM2x0U1dGd2JrNXhhRVpOUVRCSFExTnhSMU5KWWpNS1JGRkZRa04zVlVGQk5FbENRVkZEU2sweFZFRkNSVll4VWtWRFdtUjNZMUJXZEZJelZtZ3liM1Z3WkhoVWN6QTBiMHBYVjJwaU1XUk1MME5IVmlzNVV3cDZNSHB3V205S0t6QkhaVUpDYjNCbVdHMDJSa2RUVUhWRldUVmhNR2xOTVZKb2FYTTNTblpCZDNacE1XcFZkM1JYUlU5bFYwVnJlSG92VDFKS1lpdHdDakpPU1haRGJ6YzNjRVl4YVRCUlZuSm5XRkJhZFROeGMwRk1WMXB4TTFCcGVtbE9lRFk0YjJJMlFsaGFZa2xPVkc5dU5GTnZkMmhhT0VJeGJUazVZaklLYWpWNE5tVXdibkV6Y0ZWWkswUkVSblZQVTFOaU1rSXZRVUUzVlhCdlVVbG9iVVp2V2tKc2RsUldMMGhTYnpnclRXSk1MMVZ2WlhGS1FUZEVPVEZTU3dwUll6WTJaMHBYYVdGM01FUTVSMFZQWTBKNVpuUjBaV1JhWlZCa01rUnVOSHBrZFZJNFZIRXZObTFXY0VKa1lqa3hjblpLV1RKeVJGZGlPVFpOZFZob0NtRkJXV2d6WWpsdE0yczBaemczUm10Sk1rcG9SazkzYUN0alJVaFFaMkpsZWpaMWVBb3RMUzB0TFVWT1JDQkRSVkpVU1VaSlEwRlVSUzB0TFMwdENnPT0KS1VCRUxFVF9FWFRSQV9BUkdTPSctLW5vZGUtbGFiZWxzPW5vZGUuazhzLmF3cy9jYXBhY2l0eS10eXBlPXNwb3QnCi9ldGMvZWtzL2Jvb3RzdHJhcC5zaCAkQ0xVU1RFUl9OQU1FIC0ta3ViZWxldC1leHRyYS1hcmdzICRLVUJFTEVUX0VYVFJBX0FSR1MgLS1iNjQtY2x1c3Rlci1jYSAkQjY0X0NMVVNURVJfQ0EgLS1hcGlzZXJ2ZXItZW5kcG9pbnQgJEFQSV9TRVJWRVJfVVJMIA=="
        BlockDeviceMappings:
          - Ebs:
              VolumeSize: 120
              VolumeType: gp3
            DeviceName: /dev/xvda
        # The SecurityGroup must be associated with the cluster VPC
        SecurityGroupIds:
          - sg-0c71150033fdab49e 
      LaunchTemplateName: KarpenterCustomLaunchTemplate