apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  provider:
    instanceProfile: KarpenterNodeInstanceProfile-karpenter-demo
    launchTemplate: KarpenterCustomLaunchTemplate
  # taints:
  #   - key: example.com/special-taint
  #     effect: NoSchedule
  labels:
    billing-team: my-team
  requirements:
    - key: "node.kubernetes.io/instance-type" 
      operator: In
      values: ["m4.2xlarge", "m5dn.16xlarge", "m5.4xlarge", "m5.4xlarge", "m4.10xlarge"]
    - key: "topology.kubernetes.io/zone" 
      operator: In
      values: ["us-east-2a", "us-east-2b", "us-east-2c"]
    - key: "kubernetes.io/arch" 
      operator: In
      values: ["arm64", "amd64"]
    - key: "karpenter.sh/capacity-type" # If not included, the webhook for the AWS cloud provider will default to on-demand
      operator: In
      values: ["spot", "on-demand"]
  limits:
    resources:
      cpu: 1000
  ttlSecondsAfterEmpty: 30